language: java
jdk: oraclejdk7

before_install:
    - export ANDROID_API_LEVEL=18
    - export ANDROID_SDK_TOOLS_VERSION=22.2.1
    - export ANDROID_BUILD_TOOLS_VERSION=18.1
    - export ANDROID_OS_VERSION=4.3
    - export ANDROID_TARGET=android-18
    - export ANDROID_ABI=armeabi-v7a
    - export GRADLE_VERSION=1.7
    
    # Install Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
    - wget https://dl.google.com/android/android-sdk_r$ANDROID_SDK_TOOLS_VERSION-linux.tgz
    - tar xzf android-sdk_r$ANDROID_SDK_TOOLS_VERSION-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
    
    # Install Android build tools
    - wget https://dl-ssl.google.com/android/repository/build-tools_r$ANDROID_BUILD_TOOLS_VERSION-linux.zip
    - unzip build-tools_r$ANDROID_BUILD_TOOLS_VERSION-linux.zip -d $ANDROID_HOME
    - mkdir -p $ANDROID_HOME/build-tools/
    - mv $ANDROID_HOME/android-$ANDROID_OS_VERSION $ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION
    
    # Install Android SDK components    
    - echo yes | android update sdk --filter tool --no-ui --force > /dev/null
    - echo yes | android update sdk --filter platform-tool --no-ui --force > /dev/null
    - echo yes | android update sdk --filter android-17 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter android-18 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter sysimg-18 --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null
    - echo yes | android update sdk --filter `android list sdk --no-ui | grep 'Google Repository' | cut -d '-' -f 1 | tr -d ' '` --no-ui --force > /dev/null
    # - echo yes | android update sdk --filter extra-google-play-services --no-ui --force > /dev/null
    
    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &
    
before_script:
    - chmod +x ci/wait_for_emulator.sh
    - ci/wait_for_emulator.sh
    - adb shell input keyevent 82 &
    
script:
    - ./gradlew connectedInstrumentTest -d -i -s
